// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI56xOKbRb_hKXr7pf_KJ39kKPMs06hKo',
    appId: '1:822329598577:web:98448a6880fdef2d61f1d0',
    messagingSenderId: '822329598577',
    projectId: 'sfc-arena',
    authDomain: 'sfc-arena.firebaseapp.com',
    storageBucket: 'sfc-arena.firebasestorage.app',
    measurementId: 'G-VLXQ0H92JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEpK40qRIgb45dhD-Be_giJIHWfAzOSc',
    appId: '1:822329598577:android:90b2a9884fca2e8f61f1d0',
    messagingSenderId: '822329598577',
    projectId: 'sfc-arena',
    storageBucket: 'sfc-arena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuL1PQIDEkFfYp2EKQuJ2f5dwS3lWMAEI',
    appId: '1:822329598577:ios:9c1fced2e5f0aba661f1d0',
    messagingSenderId: '822329598577',
    projectId: 'sfc-arena',
    storageBucket: 'sfc-arena.firebasestorage.app',
    iosBundleId: 'com.example.socialGameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuL1PQIDEkFfYp2EKQuJ2f5dwS3lWMAEI',
    appId: '1:822329598577:ios:9c1fced2e5f0aba661f1d0',
    messagingSenderId: '822329598577',
    projectId: 'sfc-arena',
    storageBucket: 'sfc-arena.firebasestorage.app',
    iosBundleId: 'com.example.socialGameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI56xOKbRb_hKXr7pf_KJ39kKPMs06hKo',
    appId: '1:822329598577:web:e4be8b02898b6b3461f1d0',
    messagingSenderId: '822329598577',
    projectId: 'sfc-arena',
    authDomain: 'sfc-arena.firebaseapp.com',
    storageBucket: 'sfc-arena.firebasestorage.app',
    measurementId: 'G-RP77BJEV9T',
  );

}